import { ContentCarousel } from "@/components/ContentCarousel";
import { Navbar } from "@/components/Navbar";
import { Products } from "@/components/Products";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ContentCarousel />
        <Products />
        {/*<Form />
        <Footer /> */}
      </body>
    </html>
  );
}
