<<<<<<< HEAD
import { AboutUs } from "@/components/AboutUs";
import { ContentCarousel } from "@/components/ContentCarousel";
import { Footer } from "@/components/Footer";
import { Form } from "@/components/Form";
import { Navbar } from "@/components/Navbar";
import { Products } from "@/components/Products";
import { Services } from "@/components/Services";
=======
import { ContentCarousel } from "@/components/ContentCarousel";
import { Navbar } from "@/components/Navbar";
import { Products } from "@/components/Products";
>>>>>>> f2f983a8682826c550c79933304788ca0244588c
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "El porvenir",
  description: "Generate hardware software the porvenir",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> f2f983a8682826c550c79933304788ca0244588c
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ContentCarousel />
        <Products />
<<<<<<< HEAD
        <Services />
        <AboutUs />
        <Form />
        <Footer />
=======
        {/*<Form />
        <Footer /> */}
>>>>>>> f2f983a8682826c550c79933304788ca0244588c
      </body>
    </html>
  );
}
